/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    Poseidon: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      abi: [
        {
          inputs: [
            {
              internalType: "uint256[1]",
              name: "",
              type: "uint256[1]",
            },
          ],
          name: "hash",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    YourContract: {
      address: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
      abi: [
        {
          inputs: [
            {
              internalType: "uint256[1]",
              name: "",
              type: "uint256[1]",
            },
          ],
          name: "hash",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              components: [
                {
                  internalType: "uint256[2]",
                  name: "_pA",
                  type: "uint256[2]",
                },
                {
                  internalType: "uint256[2][2]",
                  name: "_pB",
                  type: "uint256[2][2]",
                },
                {
                  internalType: "uint256[2]",
                  name: "_pC",
                  type: "uint256[2]",
                },
                {
                  internalType: "uint256[56]",
                  name: "_pubSignals",
                  type: "uint256[56]",
                },
              ],
              internalType: "struct YourContract.ProofArgs",
              name: "proof",
              type: "tuple",
            },
            {
              internalType: "uint256",
              name: "beauty",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "biome",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "intelligence",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "jump",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "speed",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "rarity",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "owner",
              type: "uint256",
            },
          ],
          name: "verifyAndExtractFrog",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256[2]",
              name: "_pA",
              type: "uint256[2]",
            },
            {
              internalType: "uint256[2][2]",
              name: "_pB",
              type: "uint256[2][2]",
            },
            {
              internalType: "uint256[2]",
              name: "_pC",
              type: "uint256[2]",
            },
            {
              internalType: "uint256[56]",
              name: "_pubSignals",
              type: "uint256[56]",
            },
          ],
          name: "verifyProof",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {
        verifyProof: "contracts/Groth16Verifier.sol",
        hash: "contracts/Poseidon.sol",
      },
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
